os: osx

osx_image: xcode9.4

language: node_js

node_js: "10"

addons:
  chrome: stable

before_install:
  - brew install git-lfs

install:
  - npm install

before_script:
  - git lfs pull
  - export NODE_OPTIONS=-–max_old_space_size=4096

script:
  - npm run lint
  - travis_wait npm run build:prod
#  - travis_wait npm run package
