os: osx

osx_image: xcode9.4

language: node_js

node_js: "10"

addons:
  chrome: stable

before_install:
  - brew install git-lfs

install:
  - npm install

before_script:
  - git lfs pull

script:
  - npm run lint
  - travis_wait npm run package
