name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Code signing with Software Trust Manager
#        uses: digicert/ssm-code-signing@v1.1.1

      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        env:
          DEBUG: electron-builder
          SM_HOST: https://clientauth.one.digicert.com/
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: D:\\Certificate_pkcs12.p12
          SM_CLIENT_CERT_FILE_B64: ${{ secrets.SM_CLIENT_CERT_FILE_B64 }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
        run: |
          Set-Content -Path "client_cert_base64.txt" -Value $env:SM_CLIENT_CERT_FILE_BASE64
          certutil -decode "client_cert_base64.txt" "$env:SM_CLIENT_CERT_FILE"
          smctl healthcheck
        timeout-minutes: 90
