name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Code signing with Software Trust Manager
#        uses: digicert/ssm-code-signing@v1.1.1

      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        env:
          DEBUG: electron-builder
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SM_HOST: ${{ secrets.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: D:\\Certificate_pkcs12.p12
          SM_CLIENT_CERT_FILE_B64: ${{ secrets.SM_CLIENT_CERT_FILE_B64 }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          SM_KEYPAIR_ALIAS: ${{ secrets.SM_KEYPAIR_ALIAS }}
        run: |
          echo %SM_CLIENT_CERT_FILE_B64% > client_cert_base64.txt
          certutil -decode client_cert_base64.txt %SM_CLIENT_CERT_FILE%
        timeout-minutes: 90
